function T = getTransformMatrices(theta)
% Returns the transform matrices of each joint based on the input theta
% values

    % Get arm dimensions from constant file
    armDims = getArmDimensions();
        
    % World frame
    T(:,:,1) = eye(4); 
    % Base of robot s.t. x axis pointing into link
    T(:,:,2) = getDHTransform(theta(1), ...     % Base of first servo
                              0, ... 
                              0, ...
                              34);
    T(:,:,3) = getDHTransform(pi/2, ...         % Changing orientation
                              pi/2, ... 
                              0, ... 
                              0); 
    T(:,:,4) = getDHTransform(theta(2), ...     % Base of second servo
                              0, ... 
                              43, ... 
                              0); 
    T(:,:,5) = getDHTransform(-pi/2, ...        % Elbow between servos
                              0, ... 
                              armDims.L1, ... 
                              0); 
    T(:,:,6) = getDHTransform(theta(3), ...     % Base of third servo
                              0, ... 
                              armDims.L2, ... 
                              0);
    T(:,:,7) = getDHTransform(theta(4), ...     % Base of fourth servo
                              0, ... 
                              armDims.L3, ... 
                              0); 
    T(:,:,8) = getDHTransform(0, ...            % End effector
                              0, ... 
                              armDims.L4, ... 
                              0); 
end

